x-airflow-environment: &airflow-environment
  environment:
    - AIRFLOW_USER
    - AIRFLOW_PASSWORD
    - AIRFLOW__CORE__FERNET_KEY=_vlbm4VJwSvCYuBSHlOGPqDQyWkgrSp47P8ou6zP0zY=
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${AIRFLOW_POSTGRES_USER}:${AIRFLOW_POSTGRES_PASSWORD}@${AIRFLOW_POSTGRES_HOST}:${AIRFLOW_POSTGRES_PORT}/${AIRFLOW_POSTGRES_DB}
    - AIRFLOW__CORE__STORE_SERIALIZED_DAGS=True
    - AIRFLOW__CORE__STORE_DAG_CODE=True
    - DBT_POSTGRES_USER
    - DBT_POSTGRES_PASSWORD
    - DBT_POSTGRES_DB
    - DBT_POSTGRES_HOST
    - DBT_POSTGRES_PORT
    - LOCAL_STORAGE=/opt/storage
    # The following configurations work for docker resource limit of 12gb and 6cpu's (adjust it accordingly)
    - AIRFLOW__CORE__PARALLELISM=64
    - AIRFLOW__CORE__DAG_CONCURRENCY=64
    - AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG=64
  image: feluelle/fdb_airflow:latest
x-airflow-volumes: &airflow-volumes
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./storage:/opt/storage
    - ./dbt:/opt/dbt

version: '3.8'
services:
  fdb-dbt-db:
    image: library/postgres:latest
    container_name: ${DBT_POSTGRES_HOST}
    environment:
      - POSTGRES_USER=${DBT_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DBT_POSTGRES_PASSWORD}
      - POSTGRES_DB=${DBT_POSTGRES_DB}
    ports:
      - 55432:${DBT_POSTGRES_PORT}
    restart: always
  fdb-airflow-db:
    image: library/postgres:latest
    container_name: ${AIRFLOW_POSTGRES_HOST}
    environment:
      - POSTGRES_USER=${AIRFLOW_POSTGRES_USER}
      - POSTGRES_PASSWORD=${AIRFLOW_POSTGRES_PASSWORD}
      - POSTGRES_DB=${AIRFLOW_POSTGRES_DB}
    ports:
      - 55433:${AIRFLOW_POSTGRES_PORT}
    restart: always
  fdb-airflow-db-init:
    <<: *airflow-environment
    build: .
    container_name: fdb_airflow_db_init
    entrypoint: /bin/bash
    command:
      - -c
      - airflow users list || (
          airflow db upgrade &&
          airflow users create --role Admin --username ${AIRFLOW_USER} --email airflow@apache.org --firstname Airflow --lastname Apache --password ${AIRFLOW_PASSWORD}
        )
    restart: on-failure
    depends_on:
      - fdb-airflow-db
  fdb-airflow-webserver:
    <<: *airflow-environment
    container_name: fdb_airflow_webserver
    command: webserver
    ports:
      - 58080:8080  # airflow webserver
      - 58081:8081  # dbt docs serve
    <<: *airflow-volumes
    depends_on:
      - fdb-airflow-db-init
    restart: always
  fdb-airflow-scheduler:
    <<: *airflow-environment
    container_name: fdb_airflow_scheduler
    command: scheduler
    <<: *airflow-volumes
    depends_on:
      - fdb-airflow-db-init
    restart: always